Header story layout
UCF/Main-Site-Theme pull request #326
Opened 2021-03-11 17:05 UTC by rjucf

**Description**

Adding a header layout for the UCF news shortcode.

**Motivation and Context**

Client request

**How Has This Been Tested?**

Tested in Dev

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**

- [x] My code follows the code style of this project.
- [ ] My change requires an update to the documentation.
- [ ] I have updated the documentation accordingly.

2021-03-11 19:15 UTC, cjg89 requested changes

2021-03-11 19:15 UTC, cjg89 commented on src/scss/components/_layout-header-card.scss
> +.ucf-news.header-card-layout {
Can we add these styles to src/scss/components/_news.scss instead of a new file?

2021-03-11 19:15 UTC, cjg89 commented on includes/ucf-news-layouts.php
> +        var_dump( 'Adding Header Card layout.' );
`var_dump()` should be removed.

2021-03-11 19:15 UTC, cjg89 commented on includes/ucf-news-layouts.php
> +			$item_img = UCF_News_Common::get_story_img_tag( $item );
Let's make sure the project readme is updated to move the UCF News Plugin from the Supported Plugins list to the Required Plugins list, now that we are depending on the `UCF_News_Common` class being defined here.

2021-03-11 19:15 UTC, cjg89 commented on includes/ucf-news-layouts.php
> +					<h3 class="ucf-news-header-card-subtitle"><?php echo $item->excerpt->rendered; ?></h3>
Subtitle text should be wrapped in a `div` or `p` instead of a heading.

2021-03-11 19:15 UTC, cjg89 commented on includes/ucf-news-layouts.php
> +					<h3 class="ucf-news-header-card-title"><?php echo $item->title->rendered; ?></h3>
Consider using a `<strong>` tag instead of a heading for the story title text to avoid heading order issues.

2021-03-11 20:34 UTC, jmbarne3 approved these changes

2021-03-12 17:06 UTC, cadie approved these changes

2021-03-15 13:34 UTC, cjg89 approved these changes

2021-03-18 14:21 UTC, merged